apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongo
spec:
 serviceName: mongo
 replicas: 3
 selector:
    matchLabels:
      app: mongo
 template:
   metadata:
     labels:
       app: mongo
   spec:
     terminationGracePeriodSeconds: 10
     affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mongo
            topologyKey: "kubernetes.io/hostname"
     containers:
       - name: mongo
         image: us-central1-docker.pkg.dev/menna-402718/project-images/mongo
         command:
         - mongod
         - "--bind_ip_all"
         - "--replSet"
         - rs0  
         ports:
           - containerPort: 27017
         volumeMounts:
           - name: persistent-storage
             mountPath: /data/db
 volumeClaimTemplates:
 - metadata:
     name: persistent-storage
     annotations:
       volume.beta.kubernetes.io/storage-class: "storage"
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 2Gi