FROM node

WORKDIR /app

# Copy package.json 
COPY ./package.json .

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Expose the port
EXPOSE 3000

# Start the app
CMD [ "node", "index.js" ]